---

_vendor:   supertanuki
_app:      alertme
_app_dir:  /srv/app
_app_host: "{{ _app ~ ('.' ~ _vendor if _vendor else '') }}"

########
# Motd #
########

elao_motd_template: template/elao.j2
elao_motd:          California - 1993

############
# Timezone #
############

elao_timezone: Etc/UTC

#######
# Env #
#######

elao_env:
  - SYMFONY_ENV: "{{ _env }}"

#######
# Apt #
#######

elao_apt_update: true

elao_apt_components: ['main']

elao_apt_sources_list_template: sources_list/debian.list.j2

elao_apt_repositories_exclusive: true
elao_apt_repositories:
  - debian_security
  - debian_updates

elao_apt_preferences:
  - ruby@bearstech
  - git@debian_backports
  - ~@dotdeb:100
  #- php@dotdeb # Php 5.4
  #- php@dotdeb_php55
  - php@dotdeb_php56
  - nginx@nginx
  #- nodejs@nodesource_0_10
  - nodejs@nodesource_0_12
  #- nodejs@nodesource_4
  # App
  - mysql@dotdeb
  #- postgresql@postgresql
  #- redis@dotdeb
  #- elasticsearch@elasticsearch_1_7
  #- mongodb@mongodb_3_0
  #- mongodb@mongodb_3_2

elao_apt_packages: []

#######
# Ssh #
#######

elao_ssh_config_sshd_template: config/sshd/{{ _env }}.j2

elao_ssh_config_template: config/{{ _env }}.j2
elao_ssh_config: []

#######
# Git #
#######

elao_git_config_template: config/{{ _env }}.j2

#############
# Oh my zsh #
#############

elao_ohmyzsh_users:
  - user:     "{{ _user }}"
    template: users/{{ _env }}.j2
    config:
      - |
        elao_php_xdebug () {
            if [[ $1 == on ]]; then sudo rename -v 's/20-xdebug.ini.off/20-xdebug.ini/' /etc/php5/*/conf.d/20-xdebug.ini.off
            else sudo rename -v 's/20-xdebug.ini/20-xdebug.ini.off/' /etc/php5/*/conf.d/20-xdebug.ini; fi
            sudo service php5-fpm restart
        }
        elao_nginx_timeout () {
            if [[ $1 == off ]]; then sudo sed -ri 's/fastcgi_read_timeout (.*);$/fastcgi_read_timeout 999s;#origin\1/' /etc/nginx/conf.d/php_fpm_params
            else sudo sed -ri 's/^fastcgi_read_timeout 999s;#origin(.*)/fastcgi_read_timeout \1;/' /etc/nginx/conf.d/php_fpm_params; fi
            sudo /etc/init.d/nginx restart
        }
      - ZSH_THEME: elao-dev
      - plugins: (git debian common-aliases history history-substring-search npm composer symfony2)
      - export PATH: ./bin:$PATH
      - cd {{ _app_dir }}/symfony

#########
# Files #
#########

_all_files: []

#######
# Gem #
#######

elao_gem_packages:
  - name:    capifony
    version: ~> 2.8

#############
# PhantomJS #
#############

elao_phantomjs_config_template: config/{{ _env }}.j2

###############
# Mailcatcher #
###############

elao_mailcatcher_config_template: config/{{ _env }}.j2

##########
# Log.io #
##########

elao_logio_config_harvester:
  - nodeName: App
  - logStreams:
    - php:
      - "{{ elao_php_log_dir }}/error.log"
    - nginx:
      - "{{ elao_nginx_log_dir }}/app.access.log"
      - "{{ elao_nginx_log_dir }}/app.error.log"
    - symfony:
      - /var/log/symfony/dev.log
      - /var/log/symfony/test.log
      - /var/log/symfony/prod.log

#########
# MySql #
#########

elao_mysql_configs_exclusive: true
elao_mysql_configs:
  - file: my.cnf
    template: configs/{{ _env }}.cnf.j2

##############
# PhpMyAdmin #
##############

#elao_phpmyadmin_version: <4.5 # Php 5.4

elao_phpmyadmin_config_template: config/{{ _env }}.inc.php.j2

##############
# PostgreSQL #
##############

#elao_postgresql_version: 9.4

#elao_postgresql_config_template: config/{{ _env }}.conf.j2

#elao_postgresql_config_hba_template: config/hba/{{ _env }}.conf.j2

##############
# PhpPgAdmin #
##############

#elao_phppgadmin_config_template: config/{{ _env }}.inc.php.j2

#########
# Redis #
#########

#elao_redis_config_template: config/{{ _env }}.conf.j2

#################
# PhpRedisAdmin #
#################

#elao_phpredisadmin_config_template: config/{{ _env }}.inc.php.j2

###########
# MongoDB #
###########

#elao_mongodb_config_template: config/{{ _env }}.conf.j2

#######
# Php #
#######

elao_php_version: 5

elao_php_sapis: ['cli', 'fpm']

elao_php_fpm_pools_exclusive: true
elao_php_fpm_pools:
  - file:     www.conf
    template: fpm_pools/www_{{ _env }}.conf.j2

elao_php_extensions:
  # Dev
  - xdebug
  # Symfony
  - intl
  - curl
  # App
  - mysqlnd
  #- pgsql

elao_php_configs_exclusive: true
#elao_php_configs_global:    true # Php 5.4
elao_php_configs:
  - file: 50-xdebug.ini
    template: configs/xdebug_{{ _env }}.ini.j2
  - file: 50-opcache.ini
    template: configs/opcache_{{ _env }}.ini.j2
  - file: 60-config.ini
    template: configs/{{ _env }}.ini.j2
    config:
      - date.timezone: UTC
      # App

elao_php_applications:
  - composer
  # Dev
  - php-cs-fixer
  - phpcs
  # App
  #- phpunit
  #- phpunit@5.0.0
  #- openl10n@0.2.0

#########
# Nginx #
#########

elao_nginx_config_template: config/http_{{ _env }}.conf.j2

elao_nginx_configs_exclusive: true
_all_nginx_configs:
  # Php fpm
  - file:     php_fpm_params
    template: configs/php_fpm_params_{{ _env }}.j2
  # Gzip
  - file:     gzip
    template: configs/gzip_{{ _env }}.j2
  # Default 404
  - file:     00-default.conf
    template: configs/server_{{ _env }}.conf.j2
    config:
      - return: 404
  # App
  - file:     "{{ _app_host }}.conf"
    template: configs/server_{{ _env }}.conf.j2
    config:
      - server_name: "{{ _app_host }}.dev"
      - root:        "{{ _app_dir }}/symfony/web"
      - access_log:  "{{ elao_nginx_log_dir }}/app.access.log"
      - error_log:   "{{ elao_nginx_log_dir }}/app.error.log"
      - include:     conf.d/gzip
      - location /:
        - try_files: $uri /app.php$is_args$args
      - location ~ ^/(app(_[-\w]+)?)\.php(/|$):
        - include: conf.d/php_fpm_params
        #- internal;

#######
# Npm #
#######

elao_npm_packages:
  #- name:    bower
  #  version: 1
  - name:    gulp
    version: 3

########
# Cron #
########

#elao_cron_files:
#  - file: app
#    user: "{{ elao_php_user }}"
#    jobs:
#      # Do foo bar
#      - name:   foo-bar
#        job:    "php {{ _app_dir }}/symfony/bin/console app:foo:bar --env={{ _env }}"
#        minute: 0
#        hour:   7
#        # Dev
#        state:  absent

##############
# Supervisor #
##############

#elao_supervisor_config_template: config/{{ _env }}.conf.j2

#elao_supervisor_configs_exclusive: true
#elao_supervisor_configs:
#  - file:     inet-http-server.conf
#    template: configs/inet_http_server_{{ _env }}.conf.j2
#  - file:     app.conf
#    template: configs/program_{{ _env }}.conf.j2
#    config:
#      - foo-bar:
#        - command:         php bin/console app:foo:bar --env={{ _env }} --no-interaction -vv
#        - directory:       "{{ _app_dir }}/symfony"
#        - user:            "{{ elao_php_user }}"
#        - autorestart:     true
#        - stdout_logfile:  "{{ elao_supervisor_log_dir }}/foo-bar.log"
#        - redirect_stderr: true
#        - environment:     "SYMFONY_ENV=\"{{ _env }}\""
#        # Dev
#        - autostart:       false
